"""Export a quantized BFSRCNN checkpoint as a portable C99 header."""

import argparse
from pathlib import Path
import re

from models.bfsrcnn.quantization.checkpoint import (
    load_pixel_integer_checkpoint,
)
from models.common.deployment.c_data import (
    DTYPE_TO_C,
    c_identifier,
    tensor_values,
)


def render_header(
    model,
    metadata,
    checkpoint_path,
    output_path,
    symbol_prefix='bfsrcnn',
    include_guard=None,
    values_per_line=16,
):
    if values_per_line < 1:
        raise ValueError('values_per_line must be positive')
    prefix = c_identifier(symbol_prefix)
    macro_prefix = c_identifier(symbol_prefix, uppercase=True)
    if include_guard is None:
        include_guard = c_identifier(
            f'{macro_prefix}_{Path(output_path).name}', uppercase=True
        )
    elif not re.fullmatch(r'[A-Za-z_][0-9A-Za-z_]*', include_guard):
        raise ValueError('include_guard must be a valid C identifier')

    state = model.state_dict()
    total_elements = sum(tensor.numel() for tensor in state.values())
    total_bytes = sum(
        tensor.numel() * DTYPE_TO_C[tensor.dtype][1]
        for tensor in state.values()
        if tensor.dtype in DTYPE_TO_C
    )
    calibration_tile_size = metadata.get('calibration_tile_size', 0)
    calibration_tile_pad = metadata.get('calibration_tile_pad', 0)

    lines = [
        '/* Auto-generated by models.bfsrcnn.deployment.c_format. */',
        f'/* Source checkpoint: {Path(checkpoint_path).as_posix()} */',
        '/* Tensor data is flattened in PyTorch contiguous (row-major) order. */',
        '/* Logical sub-byte widths use int8_t storage; inspect the *_BITS macros. */',
        f'#ifndef {include_guard}',
        f'#define {include_guard}',
        '',
        '#include <stdint.h>',
        '',
    ]
    for name, value in model.config.items():
        lines.append(f'#define {macro_prefix}_{c_identifier(name, True)} {int(value)}')
    lines.extend([
        f'#define {macro_prefix}_CALIBRATION_TILE_SIZE {int(calibration_tile_size)}',
        f'#define {macro_prefix}_CALIBRATION_TILE_PAD {int(calibration_tile_pad)}',
        f'#define {macro_prefix}_TENSOR_COUNT {len(state)}',
        f'#define {macro_prefix}_TOTAL_ELEMENTS {total_elements}',
        f'#define {macro_prefix}_TOTAL_BYTES {total_bytes}',
        '',
    ])

    for state_name, tensor in state.items():
        if tensor.dtype not in DTYPE_TO_C:
            raise TypeError(
                f'unsupported tensor dtype for {state_name}: {tensor.dtype}'
            )
        c_type, _ = DTYPE_TO_C[tensor.dtype]
        name = c_identifier(f'{prefix}_{state_name}')
        macro = c_identifier(f'{macro_prefix}_{state_name}', uppercase=True)
        shape = tuple(tensor.shape)
        lines.append(f'/* {state_name}: shape={shape}, dtype={tensor.dtype} */')
        lines.append(f'#define {macro}_RANK {tensor.ndim}')
        for index, dimension in enumerate(shape):
            lines.append(f'#define {macro}_DIM_{index} {dimension}')
        lines.append(f'#define {macro}_SIZE {tensor.numel()}')
        lines.append(
            f'static const {c_type} {name}[{macro}_SIZE] = {{'
        )
        lines.append(tensor_values(tensor, values_per_line))
        lines.extend(['};', ''])

    lines.extend([f'#endif /* {include_guard} */', ''])
    return '\n'.join(lines), {
        'tensor_count': len(state),
        'total_elements': total_elements,
        'total_bytes': total_bytes,
    }


def export_c_header(
    checkpoint_path,
    output_path,
    symbol_prefix='bfsrcnn',
    include_guard=None,
    values_per_line=16,
):
    model, metadata = load_pixel_integer_checkpoint(checkpoint_path, 'cpu')
    text, summary = render_header(
        model,
        metadata,
        checkpoint_path,
        output_path,
        symbol_prefix,
        include_guard,
        values_per_line,
    )
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding='utf-8')
    return summary


def parse_args():
    parser = argparse.ArgumentParser(
        description='Export a pixel-domain integer BFSRCNN checkpoint as a C99 header'
    )
    parser.add_argument('--integer-weights-file', required=True)
    parser.add_argument('--output-file', required=True)
    parser.add_argument('--symbol-prefix', default='bfsrcnn')
    parser.add_argument('--include-guard')
    parser.add_argument('--values-per-line', type=int, default=16)
    return parser.parse_args()


def main():
    args = parse_args()
    summary = export_c_header(
        args.integer_weights_file,
        args.output_file,
        args.symbol_prefix,
        args.include_guard,
        args.values_per_line,
    )
    print(f'C header written to {args.output_file}')
    print(
        f"exported {summary['tensor_count']} tensors, "
        f"{summary['total_elements']} elements, "
        f"{summary['total_bytes']} data bytes"
    )


if __name__ == '__main__':
    main()
