"""Model-independent PTQ/QAT algorithms constrained by BIRA arithmetic."""

from .core import (
    MinMaxObserver,
    PowerOfTwoQuantSpec,
    SymmetricQuantSpec,
    binary_sign,
    fake_binary_sign,
    fake_quantize_power_of_two,
    fake_quantize_symmetric,
    fused_binary_rprelu,
    power_of_two_activation_exponent,
    quantize_accumulator_bias,
    quantize_double_power_of_two,
    quantize_power_of_two_weight,
    quantize_symmetric,
)
from .handlers import (
    LayerQuantSpec,
    ModuleOutputCalibrator,
    QuantizedLayer,
    discover_basic_layers,
    quantize_basic_layer,
    quantize_prelu_slope,
    sample_tensor,
)
from .calibration import (
    ObservationSpec,
    RuleCalibrator,
    calibrate_model,
)
from .plan import (
    ActivationRule,
    ApotRule,
    BinaryAffineResidualRule,
    ConstantRule,
    IntegerConvRule,
    QuantizationPlan,
    apply_quantized_state,
)

__all__ = [
    'MinMaxObserver',
    'LayerQuantSpec',
    'ObservationSpec',
    'ModuleOutputCalibrator',
    'PowerOfTwoQuantSpec',
    'SymmetricQuantSpec',
    'QuantizedLayer',
    'QuantizationPlan',
    'RuleCalibrator',
    'ActivationRule',
    'ApotRule',
    'BinaryAffineResidualRule',
    'ConstantRule',
    'IntegerConvRule',
    'binary_sign',
    'calibrate_model',
    'fake_binary_sign',
    'fake_quantize_power_of_two',
    'fake_quantize_symmetric',
    'fused_binary_rprelu',
    'discover_basic_layers',
    'power_of_two_activation_exponent',
    'quantize_accumulator_bias',
    'quantize_basic_layer',
    'quantize_double_power_of_two',
    'quantize_power_of_two_weight',
    'quantize_prelu_slope',
    'quantize_symmetric',
    'sample_tensor',
    'apply_quantized_state',
]
